project:
  type: website
  output-dir: Docs

website:
  title: "SESAY Jr. Jeremy S"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Education.qmd
      - Experience.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



